import { Food } from '../services/food.service';
import fs from 'fs';
import path from 'path';

const foods: Array<Food> = [
  {
    name: 'Maçã Fugi',
    enName: 'apple',
    id: 1,
    gi: 25,
    gl: 3,
    image: '/images/food/apple.svg',
    calories: 52,
    carbohydrates: 10,
  },
  {
    name: 'Pêra',
    enName: 'pear',
    id: 2,
    gi: 38,
    image: '/images/food/pear.svg',
    calories: 57,
  },
  {
    name: 'Banana Prata',
    enName: 'silver-banana',
    id: 3,
    gi: 39,
    gl: 8,
    image: '/images/food/banana.svg',
    calories: 89,
    carbohydrates: 28,
  },
  {
    name: 'Arroz Branco',
    enName: 'white-rice',
    id: 4,
    gi: 81,
    gl: 18,
    carbohydrates: 32,
    image: '/images/food/rice.svg',
    calories: 130,
  },
  {
    name: 'Feijão',
    enName: 'bean',
    id: 5,
    gi: 29,
    image: '/images/food/bean.svg',
    calories: 76,
  },
  {
    name: 'Banana Nanica',
    enName: 'nanica-banana',
    id: 6,
    gi: 70,
    gl: 14,
    image: '/images/food/banana.svg',
    calories: 89,
    carbohydrates: 28,
  },
  {
    name: 'Banana Mysore',
    enName: 'mysore-banana',
    id: 7,
    gi: 87,
    gl: 6,
    image: '/images/food/banana.svg',
    calories: 89,
    carbohydrates: 12,
  },
  {
    name: 'Suco de Laranja',
    enName: 'oragen-juice',
    id: 8,
    gi: 41,
    gl: 6,
    image: '/images/food/orange-juice.svg',
    calories: 0,
    carbohydrates: 14,
  },
  {
    name: 'Polenta',
    enName: 'polenta',
    id: 9,
    gi: 74,
    gl: 11,
    image: '/images/food/polenta.svg',
    calories: 0,
    carbohydrates: 21,
  },
  {
    name: 'Pão Francês',
    enName: 'bread-roll',
    id: 10,
    gi: 100,
    gl: 14,
    image: '/images/food/bread-roll.svg',
    calories: 0,
    carbohydrates: 20,
  },
  {
    name: 'Morango',
    enName: 'strawberry',
    id: 11,
    gi: 53,
    gl: 2,
    image: '/images/food/strawberry.svg',
    calories: 0,
    carbohydrates: 6,
  },
  {
    id: 12,
    name: 'pastel',
    enName: 'pasty',
    image: '/images/food/pasty.svg',
    description: 'pastel de carne, frito',
    aminoAcids: {
      tryptophan: 0.12,
      threonine: 0.3,
      isoleucine: 0.41,
      leucine: 0.81,
      lysine: 0.39,
      methionine: 0.19,
      cystine: 0.07,
      phenylalanine: 0.5,
      tyrosine: 0.36,
      valine: 0.5,
      arginine: 0.41,
      histidine: 0.18,
      alanine: 0.31,
      asparticAcid: 0.54,
      glutamicAcid: 3.37,
      glycine: 0.3,
      proline: 0.18,
      serine: 0.47,
    },
  },
  {
    id: 13,
    name: 'alho',
    enName: 'garlic',
    image: '/images/food/garlic.svg',
    description: 'Alho-poró, cru',
    aminoAcids: {
      tryptophan: 0.01,
      threonine: 0.03,
      isoleucine: 0.04,
      leucine: 0.07,
      lysine: 0.08,
      methionine: 0.01,
      cystine: 0,
      phenylalanine: 0.05,
      tyrosine: 0.06,
      valine: 0.05,
      arginine: 0.08,
      histidine: 0.02,
      alanine: 0.06,
      asparticAcid: 0.05,
      glutamicAcid: 0.18,
      glycine: 0.05,
      proline: 0.03,
      serine: 0.04,
    },
  },
  {
    id: 14,
    enName: 'lettuce',
    name: 'alface',
    image: '/images/food/lettuce.svg',
    description: 'Alface, roxa, crua',
    aminoAcids: {
      tryptophan: 0,
      threonine: 0.03,
      isoleucine: 0.03,
      leucine: 0.06,
      lysine: 0.05,
      methionine: 0.01,
      cystine: 0,
      phenylalanine: 0.04,
      tyrosine: 0.04,
      valine: 0.04,
      arginine: 0.06,
      histidine: 0.02,
      alanine: 0.05,
      asparticAcid: 0.05,
      glutamicAcid: 0.11,
      glycine: 0.04,
      proline: 0.03,
      serine: 0.03,
    },
  },
  {
    id: 15,
    name: 'Presunto',
    enName: 'ham',
    image: '/images/food/ham.svg',
    description: 'Presunto, sem capa de gordura',
    aminoAcids: {
      tryptophan: 0.15,
      threonine: 0.71,
      isoleucine: 0.69,
      leucine: 1.15,
      lysine: 1.28,
      methionine: 0.48,
      cystine: 0.22,
      phenylalanine: 0.63,
      tyrosine: 0.55,
      valine: 0.72,
      arginine: 1.2,
      histidine: 0.89,
      alanine: 0.82,
      asparticAcid: 1.37,
      glutamicAcid: 2.36,
      glycine: 0.73,
      proline: 0.65,
      serine: 0.68,
    },
  },
];

fs.writeFileSync(
  path.resolve(__dirname, 'food.json'),
  JSON.stringify({ foods })
);
